function ggParamByName(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?&]"+name+"=([^&#]*)"),results=regex.exec(location.search);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "));}
jQuery(document).ready(function(){var inf_field_FirstName=ggParamByName('inf_field_FirstName');if(!inf_field_FirstName.length){inf_field_FirstName=ggParamByName('Contact0FirstName');}
var inf_field_LastName=ggParamByName('inf_field_LastName');if(!inf_field_LastName.length){inf_field_LastName=ggParamByName('Contact0LastName');}
var inf_field_Email=ggParamByName('inf_field_Email');if(!inf_field_Email.length){inf_field_Email=ggParamByName('Contact0Email');}
var inf_field_Phone1=ggParamByName('inf_field_Phone1');if(!inf_field_Phone1.length){inf_field_Phone1=ggParamByName('Contact0Phone1');}
var inf_field_StreetAddress1=ggParamByName('inf_field_StreetAddress1');if(!inf_field_StreetAddress1.length){inf_field_StreetAddress1=ggParamByName('Contact0StreetAddress1');}
var inf_field_StreetAddress2=ggParamByName('inf_field_StreetAddress2');if(!inf_field_StreetAddress2.length){inf_field_StreetAddress2=ggParamByName('Contact0StreetAddress2');}
var inf_field_City=ggParamByName('inf_field_City');if(!inf_field_City.length){inf_field_City=ggParamByName('Contact0City');}
var inf_field_State=ggParamByName('inf_field_State');if(!inf_field_State.length){inf_field_State=ggParamByName('Contact0State');}
var inf_field_PostalCode=ggParamByName('inf_field_PostalCode');if(!inf_field_PostalCode.length){inf_field_PostalCode=ggParamByName('Contact0PostalCode');}
var inf_field_Country=ggParamByName('inf_field_Country');if(!inf_field_Country.length){inf_field_Country=ggParamByName('Contact0Country');}
if(jQuery("input[name='inf_field_Email']").length||jQuery("input[name='Contact0FirstName']").length){jQuery("input[name='inf_field_FirstName'],input[name='Contact0FirstName']").val(inf_field_FirstName);jQuery("input[name='inf_field_LastName'],input[name='Contact0LastName']").val(inf_field_LastName);jQuery("input[name='inf_field_Email'],input[name='Contact0Email']").val(inf_field_Email);jQuery("input[name='inf_field_Phone1'],input[name='Contact0Phone1']").val(inf_field_Phone1);jQuery("input[name='inf_field_StreetAddress1'],input[name='Contact0StreetAddress1']").val(inf_field_StreetAddress1);jQuery("input[name='inf_field_StreetAddress2'],input[name='Contact0StreetAddress2']").val(inf_field_StreetAddress2);jQuery("input[name='inf_field_City'],input[name='Contact0City']").val(inf_field_City);jQuery("input[name='inf_field_State'],input[name='Contact0State']").val(inf_field_State);jQuery("input[name='inf_field_PostalCode'],input[name='Contact0PostalCode']").val(inf_field_PostalCode);jQuery("input[name='inf_field_Country'],input[name='Contact0Country']").val(inf_field_Country);}});jQuery(document).ready(function(){if(jQuery("input[name='inf_field_Email']").length||jQuery("input[name='Contact0FirstName']").length){jQuery("input[name='inf_field_FirstName'], input[name='Contact0FirstName']").prop('required',true);jQuery("input[name='inf_field_LastName'], input[name='Contact0LastName']").prop('required',true);jQuery("input[name='inf_field_Email'], input[name='Contact0Email']").prop('required',true);if(jQuery("input[name='inf_field_Email']").prop('type')!='hidden'){jQuery("input[name='inf_field_Email']").prop('type','email');}
if(jQuery("input[name='Contact0Email']").prop('type')!='hidden'){jQuery("input[name='Contact0Email']").prop('type','email');}
jQuery(".infusion-submit").addClass("center-text");}
jQuery(".nolabel input[name='inf_field_FirstName'], .nolabel input[name='Contact0FirstName']").prop('placeholder','First Name');jQuery(".nolabel input[name='inf_field_LastName'], .nolabel input[name='Contact0LastName']").prop('placeholder','Last Name');jQuery(".nolabel input[name='inf_field_Email'], .nolabel input[name='Contact0Email']").prop('placeholder','Your Email');jQuery(".nolabel input[name='inf_field_Phone1'], .nolabel input[name='Contact0Phone1']").prop('placeholder','Phone Number');jQuery(".nolabel label").css("display","none");});

